# Notebook 1 – Introduction to NumPy

# 1. What is NumPy?

## Step 1 – Understand the Concept

NumPy stands for Numerical Python. It is a Python library used to work with numerical data and perform mathematical operations efficiently.

The main object in NumPy is the `ndarray`, which is used to store multiple values in an array.

NumPy is commonly used in Data Analytics, Scientific Computing, and Machine Learning.

## Step 2 – Demonstrate the Concept

### Simple Example

Suppose we have the marks of five students:

80, 75, 90, 85, 70

We can store these marks in a NumPy array and calculate their average.

### Real-World Example

A school can use NumPy to store students' marks and calculate average marks, highest marks, lowest marks, and other statistics.

### Business Example

A company can store monthly sales values using NumPy and calculate the average sales or compare sales between different months.

### AI/ML Use Case

In Machine Learning, data such as age, salary, experience, temperature, and other numerical features can be stored and processed using NumPy arrays.

### Data Analytics Use Case

Data analysts can use NumPy to perform calculations on numerical datasets before creating reports or visualizations.


## Step 3 – Implement the Concept (Python)

In [2]:
import numpy as np

marks = np.array([80, 75, 90, 85, 70])

average = np.mean(marks)

print("Marks:", marks)
print("Average:", average)

Marks: [80 75 90 85 70]
Average: 80.0


## Code Explanation

### What the Code Does

The code creates a NumPy array containing five student marks and calculates their average.

### Why the Function or Method Is Used

- `import numpy as np` imports NumPy.
- `np.array()` creates a NumPy array.
- `np.mean()` calculates the average.

### Expected Output

```text
Marks: [80 75 90 85 70]
Average: 80.0




# 2. Why NumPy?

## Step 1 – Understand the Concept

NumPy is used because it provides fast and efficient operations on numerical data.

Python lists can store numbers, but NumPy arrays are specially designed for numerical calculations.

NumPy provides:

- Fast numerical operations
- Efficient memory usage
- Multidimensional arrays
- Mathematical functions
- Easy array operations
- Support for Data Science and Machine Learning

## Step 2 – Demonstrate the Concept

### Simple Example

Suppose we have:

[10, 20, 30]

We want to add 5 to every value.

With NumPy, we can simply write:

`numbers + 5`

### Real-World Example

A teacher can increase all student marks by 5 bonus marks using one NumPy operation.

### Business Example

A company may increase all product prices by a fixed amount or apply a discount to thousands of products.

### AI/ML Use Case

Machine Learning often requires calculations on many numerical values. NumPy allows these operations to be performed efficiently on arrays.

### Data Analytics Use Case

Data analysts can use NumPy to perform calculations on large numerical datasets before analysis and visualization.


## Step 3 – Implement the Concept (Python)

In [3]:
import numpy as np

numbers = np.array([10, 20, 30])

result = numbers + 5

print("Original:", numbers)
print("After adding 5:", result)

Original: [10 20 30]
After adding 5: [15 25 35]


## Code Explanation

### What the Code Does

The code adds 5 to every element in the NumPy array.

### Why the Function or Method Is Used

- `np.array()` creates the numerical array.
- `numbers + 5` performs element-wise addition.
- NumPy automatically applies 5 to every element.

### Expected Output

```text
Original: [10 20 30]
After adding 5: [15 25 35]

# 3. NumPy Arrays (`ndarray`)

## Step 1 – Understand the Concept

`ndarray` means **N-dimensional array**.

It is the main data structure used by NumPy to store numerical data.

An array can have:

- 1 dimension
- 2 dimensions
- 3 dimensions
- More dimensions

NumPy arrays allow us to perform mathematical operations efficiently on multiple values.

## Step 2 – Demonstrate the Concept

### Simple Example

A student's marks can be stored as:

[80, 75, 90, 85]

This is a 1D NumPy array.

### Real-World Example

A school can store marks of many students and subjects using 2D arrays.

### Business Example

A company can represent sales data using rows for months and columns for different products.

### AI/ML Use Case

Images, numerical features, and model data can be represented using multidimensional NumPy arrays.

### Data Analytics Use Case

Numerical datasets can be stored as arrays and processed using NumPy operations.


## Step 3 – Implement the Concept (Python)

In [4]:
import numpy as np

marks = np.array([80, 75, 90, 85])

print("Array:", marks)
print("Type:", type(marks))

Array: [80 75 90 85]
Type: <class 'numpy.ndarray'>


## Code Explanation

### What the Code Does

The code creates a NumPy array and checks its data type.

### Why the Function or Method Is Used

- `np.array()` creates an `ndarray`.
- `type()` identifies the type of the object.

### Expected Output

```text
Array: [80 75 90 85]
Type: <class 'numpy.ndarray'>

# 4. Creating Arrays

## Step 1 – Understand the Concept

NumPy provides different functions for creating arrays.

Common functions are:

- `np.array()` – creates an array from existing values
- `np.zeros()` – creates an array containing zeros
- `np.ones()` – creates an array containing ones
- `np.arange()` – creates values within a range
- `np.linspace()` – creates evenly spaced values

## Step 2 – Demonstrate the Concept

### Simple Example

We can create an array such as:

[10, 20, 30]

We can also create:

[0, 0, 0, 0, 0]

using `np.zeros()`.

### Real-World Example

A school application can create an empty numerical array to store marks that will be entered later.

### Business Example

A company can create arrays of zeros to initialize sales, inventory, or monthly reporting values.

### AI/ML Use Case

Arrays created with zeros or ones can be used for initialization of numerical structures and model parameters.

### Data Analytics Use Case

`arange()` and `linspace()` can be used to create ranges of values for analysis and visualization.


## Step 3 – Implement the Concept (Python)

In [5]:
import numpy as np

array1 = np.array([10, 20, 30])
array2 = np.zeros(5)
array3 = np.ones(5)
array4 = np.arange(1, 6)
array5 = np.linspace(0, 10, 5)

print("Array:", array1)
print("Zeros:", array2)
print("Ones:", array3)
print("Arange:", array4)
print("Linspace:", array5)

Array: [10 20 30]
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Arange: [1 2 3 4 5]
Linspace: [ 0.   2.5  5.   7.5 10. ]


## Code Explanation

### What the Code Does

The code demonstrates different ways of creating NumPy arrays.

### Why the Functions Are Used

- `np.array()` creates an array from existing values.
- `np.zeros()` creates an array filled with zeros.
- `np.ones()` creates an array filled with ones.
- `np.arange()` creates values within a specified range.
- `np.linspace()` creates evenly spaced values.

### Expected Output

```text
Array: [10 20 30]
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Arange: [1 2 3 4 5]
Linspace: [ 0.   2.5  5.   7.5 10. ]

# 5. Dimensions

## Step 1 – Understand the Concept

The dimension of an array tells us how many levels of data the array contains.

Examples:

- 0D → single value
- 1D → one-dimensional sequence
- 2D → rows and columns
- 3D → collection of 2D arrays

NumPy provides the `.ndim` attribute to find the number of dimensions.

## Step 2 – Demonstrate the Concept

### Simple Example

A single number is 0D.

A list of marks is 1D.

A table containing marks is 2D.

### Real-World Example

A school can represent one student's marks as 1D and the marks of many students and subjects as 2D.

### Business Example

Monthly sales for different products can be represented as a 2D array.

### AI/ML Use Case

An image can be represented as a 2D array of pixels. A color image can be represented using a 3D array.

### Data Analytics Use Case

Understanding dimensions helps analysts correctly organize and process datasets.


## Step 3 – Implement the Concept (Python)

In [6]:
import numpy as np

array_0d = np.array(10)
array_1d = np.array([10, 20, 30])
array_2d = np.array([[10, 20], [30, 40]])
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("0D:", array_0d.ndim)
print("1D:", array_1d.ndim)
print("2D:", array_2d.ndim)
print("3D:", array_3d.ndim)

0D: 0
1D: 1
2D: 2
3D: 3


## Code Explanation

### What the Code Does

The code creates arrays with different numbers of dimensions and checks their dimensions.

### Why `.ndim` Is Used

`.ndim` returns the number of dimensions of a NumPy array.

### Expected Output

```text
0D: 0
1D: 1
2D: 2
3D: 3

# 6. Shape

## Step 1 – Understand the Concept

The **shape** of an array tells us how many elements exist along each dimension.

For a 2D array:

- First value → number of rows
- Second value → number of columns

The `.shape` attribute is used to find the shape.

## Step 2 – Demonstrate the Concept

### Simple Example

Consider:

10 20 30
40 50 60

There are 2 rows and 3 columns.

Therefore, the shape is `(2, 3)`.

### Real-World Example

A school marks table with 10 students and 5 subjects has shape `(10, 5)`.

### Business Example

A sales dataset with 1000 customers and 6 numerical features can have shape `(1000, 6)`.

### AI/ML Use Case

Machine Learning models expect input data in a particular shape. Checking shape helps avoid input dimension errors.

### Data Analytics Use Case

Shape helps analysts understand the number of records and features in a dataset.


## Step 3 – Implement the Concept (Python)

In [7]:
import numpy as np

data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Shape:", data.shape)

Shape: (2, 3)


## Code Explanation

### What the Code Does

The code creates a 2D array containing 2 rows and 3 columns and checks its shape.

### Why `.shape` Is Used

`.shape` tells us the number of elements along each dimension.

### Expected Output

```text
Shape: (2, 3)


This means:

2 rows
3 columns

# 7. Size

## Step 1 – Understand the Concept

The **size** of a NumPy array represents the total number of elements stored in it.

The `.size` attribute is used to find the total number of elements.

## Step 2 – Demonstrate the Concept

### Simple Example

A 2 × 3 array contains:

2 × 3 = 6 elements

Therefore, its size is 6.

### Real-World Example

A classroom table containing marks for 30 students and 5 subjects contains 150 values.

### Business Example

A sales table containing 12 months and 4 products contains 48 numerical values.

### AI/ML Use Case

Array size helps understand how many numerical values are being processed.

### Data Analytics Use Case

Size can help estimate the amount of data stored in an array.


## Step 3 – Implement the Concept (Python)

In [8]:
import numpy as np

data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Size:", data.size)

Size: 6


## Code Explanation

### What the Code Does

The code creates a 2D array and calculates the total number of elements.

### Why `.size` Is Used

`.size` returns the total number of elements in the complete array.

### Expected Output

```text
Size: 6

# 8. Data Types

## Step 1 – Understand the Concept

A data type tells us what kind of values an array contains.

Common types include:

- Integer
- Float
- Boolean
- String

NumPy provides the `.dtype` attribute to identify the data type.

## Step 2 – Demonstrate the Concept

### Simple Example

Student marks can be stored as integers.

Temperature values such as 36.5 can be stored as floating-point numbers.

### Real-World Example

A weather application may store temperature as float and humidity percentage as integer.

### Business Example

A company's product quantity may be stored as integer, while product price may be stored as float.

### AI/ML Use Case

Numerical Machine Learning features are commonly represented using integer or floating-point data types.

### Data Analytics Use Case

Choosing appropriate data types can improve memory usage and make numerical processing more efficient.


## Step 3 – Implement the Concept (Python)

In [9]:
import numpy as np

integers = np.array([10, 20, 30])
decimals = np.array([10.5, 20.5, 30.5])

print("Integer dtype:", integers.dtype)
print("Float dtype:", decimals.dtype)

Integer dtype: int64
Float dtype: float64


## Code Explanation

### What the Code Does

The code creates two arrays containing integer and decimal values and checks their data types.

### Why `.dtype` Is Used

`.dtype` tells us the type of data stored in the NumPy array.

### Expected Output

The first array will have an integer type and the second array will have a floating-point type.

Example:

```text
Integer dtype: int64
Float dtype: float64

# 9. Indexing

## Step 1 – Understand the Concept

Indexing is used to access a specific element from an array.

NumPy uses **zero-based indexing**.

This means:

- First element → index 0
- Second element → index 1
- Third element → index 2

## Step 2 – Demonstrate the Concept

### Simple Example

For the array:

[80, 75, 90, 85]

- Index 0 → 80
- Index 1 → 75
- Index 2 → 90
- Index 3 → 85

### Real-World Example

A teacher can access the marks of a particular student from an array.

### Business Example

A company can access the sales value of a particular month from a sales array.

### AI/ML Use Case

Indexing can be used to access a specific feature, record, or value from model input data.

### Data Analytics Use Case

Analysts can select specific values from an array for further analysis.


## Step 3 – Implement the Concept (Python)

In [10]:
import numpy as np

marks = np.array([80, 75, 90, 85])

print("First mark:", marks[0])
print("Third mark:", marks[2])

First mark: 80
Third mark: 90


## Code Explanation

### What the Code Does

The code accesses the first and third elements of the marks array.

### Why Indexing Is Used

Indexing is used when we need to access a specific element from an array.

### Expected Output

```text
First mark: 80
Third mark: 90

# 10. Slicing

## Step 1 – Understand the Concept

Slicing is used to extract a range of elements from an array.

The basic syntax is:

`array[start:stop]`

The start index is included, but the stop index is excluded.

## Step 2 – Demonstrate the Concept

### Simple Example

For:

[10, 20, 30, 40, 50]

`numbers[1:4]` returns:

[20, 30, 40]

### Real-World Example

A teacher can select marks belonging to a particular group of students.

### Business Example

A company can select sales data for a specific range of months.

### AI/ML Use Case

Slicing can be used to select a subset of features or records for model training and testing.

### Data Analytics Use Case

Analysts can select a specific portion of numerical data for detailed analysis.


## Step 3 – Implement the Concept (Python)

In [11]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

result = numbers[1:4]

print("Sliced array:", result)

Sliced array: [20 30 40]


## Code Explanation

### What the Code Does

The code extracts elements from index 1 up to, but not including, index 4.

### Why Slicing Is Used

Slicing allows us to select a specific range of elements without selecting each element individually.

### Expected Output

```text
Sliced array: [20 30 40]

# 11. Reshaping

## Step 1 – Understand the Concept

Reshaping changes the structure of an array without changing its values.

The total number of elements must remain the same.

For example, an array with 6 elements can be reshaped into:

- `(2, 3)`
- `(3, 2)`

## Step 2 – Demonstrate the Concept

### Simple Example

Original:

[1, 2, 3, 4, 5, 6]

After reshaping to `(2, 3)`:

[1, 2, 3]
[4, 5, 6]

### Real-World Example

A list of student marks can be reshaped into rows representing students and columns representing subjects.

### Business Example

Monthly sales values can be reshaped into a table where rows represent months and columns represent products.

### AI/ML Use Case

Reshaping is often required to convert data into the input shape expected by a Machine Learning or Deep Learning model.

### Data Analytics Use Case

Reshaping helps organize numerical data into a useful row-and-column structure.


## Step 3 – Implement the Concept (Python)

In [12]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5, 6])

reshaped = numbers.reshape(2, 3)

print("Original:", numbers)
print("Reshaped:")
print(reshaped)

Original: [1 2 3 4 5 6]
Reshaped:
[[1 2 3]
 [4 5 6]]


## Code Explanation

### What the Code Does

The code changes a 1D array containing 6 elements into a 2D array with 2 rows and 3 columns.

### Why `reshape()` Is Used

`reshape()` is used when we need to change the structure of an array while keeping the same values.

### Expected Output

```text
Original: [1 2 3 4 5 6]

Reshaped:
[[1 2 3]
 [4 5 6]]

# 12. Flatten

## Step 1 – Understand the Concept

Flattening converts a multidimensional array into a one-dimensional array.

NumPy provides the `flatten()` method for this purpose.

For example:

2D array → 1D array

## Step 2 – Demonstrate the Concept

### Simple Example

A 2D array:

[1, 2]
[3, 4]

After flattening:

[1, 2, 3, 4]

### Real-World Example

A table of values can be converted into one continuous list of values when a single sequence is required.

### Business Example

A company's monthly product data can be flattened into one sequence for a specific calculation.

### AI/ML Use Case

Image data can be flattened into a one-dimensional feature vector for certain Machine Learning algorithms.

### Data Analytics Use Case

Flattening can simplify multidimensional numerical data when a one-dimensional structure is required.


## Step 3 – Implement the Concept (Python)

In [13]:
import numpy as np

data = np.array([
    [1, 2],
    [3, 4]
])

flat_data = data.flatten()

print("Original:")
print(data)

print("Flattened:", flat_data)

Original:
[[1 2]
 [3 4]]
Flattened: [1 2 3 4]


## Code Explanation

### What the Code Does

The code converts a 2D array into a 1D array.

### Why `flatten()` Is Used

`flatten()` is used when we need all elements in a single one-dimensional array.

### Expected Output

```text
Original:
[[1 2]
 [3 4]]

Flattened: [1 2 3 4]

# 13. Copy vs View

## Step 1 – Understand the Concept

NumPy provides two ways to create another array from an existing array.

### Copy

A copy creates an independent array.

Changes made to the copy do not affect the original array.

### View

A view shares the same underlying data.

Changes made to the view can affect the original array

## Step 2 – Demonstrate the Concept

### Simple Example

Suppose we have an array containing student marks.

If we create a copy and change it, the original marks remain unchanged.

If we create a view and change it, the original array can also change.

### Real-World Example

A teacher may create a separate copy of marks before modifying them for analysis.

### Business Example

A company may create a copy of sales data before making changes, so that the original sales data remains safe.

### AI/ML Use Case

Understanding copy and view is important during preprocessing because accidental changes to original training data can affect model results.

### Data Analytics Use Case

Copies can be used when we need an independent dataset, while views can be useful when working with the same underlying data without creating another full copy.


## Step 3 – Implement the Concept (Python)

In [14]:
import numpy as np

original = np.array([10, 20, 30])

copy_array = original.copy()
view_array = original.view()

copy_array[0] = 100
view_array[1] = 200

print("Original:", original)
print("Copy:", copy_array)
print("View:", view_array)

Original: [ 10 200  30]
Copy: [100  20  30]
View: [ 10 200  30]


## Code Explanation

### What the Code Does

The code creates one copy and one view from the original array and modifies both.

### Why `copy()` and `view()` Are Used

- `copy()` creates independent data.
- `view()` creates another array that shares the same underlying data.

### Expected Output

```text
Original: [ 10 200  30]
Copy: [100  20  30]
View: [ 10 200  30]

# 14. Broadcasting

## Step 1 – Understand the Concept

Broadcasting allows NumPy to perform operations between arrays of compatible shapes.

It can automatically apply a single value to every element of an array.

This avoids writing manual loops for simple numerical operations.

## Step 2 – Demonstrate the Concept

### Simple Example

Suppose product prices are:

[100, 200, 300]

If we want to reduce every price by 10, we can write:

`prices - 10`

NumPy automatically applies 10 to every element.

### Real-World Example

An online store can apply the same discount amount to the prices of multiple products.

### Business Example

A company can increase salaries of all employees by a fixed amount using broadcasting.

### AI/ML Use Case

Broadcasting is used in feature scaling, normalization, mathematical transformations, and model calculations.

### Data Analytics Use Case

It can be used to apply a common adjustment or calculation to an entire numerical column or array.


## Step 3 – Implement the Concept (Python)

In [15]:
import numpy as np

prices = np.array([100, 200, 300])

discounted_prices = prices - 10

print("Original prices:", prices)
print("Discounted prices:", discounted_prices)

Original prices: [100 200 300]
Discounted prices: [ 90 190 290]


## Code Explanation

### What the Code Does

The code subtracts 10 from every product price.

### Why Broadcasting Is Used

NumPy automatically applies the single value `10` to every element in the array.

### Expected Output

```text
Original prices: [100 200 300]
Discounted prices: [ 90 190 290]

# 15. Array Operations

## Step 1 – Understand the Concept

NumPy supports mathematical operations directly on arrays.

Common operations include:

- Addition
- Subtraction
- Multiplication
- Division
- Power

For arrays with compatible shapes, these operations are usually performed element by element.

## Step 2 – Demonstrate the Concept

### Simple Example

Consider:

A = [10, 20, 30]

B = [2, 4, 5]

We can perform mathematical operations between A and B.

### Real-World Example

A student may have marks from two tests. We can add the marks or calculate differences between the tests.

### Business Example

A company can compare sales values from two different months using array operations.

### AI/ML Use Case

Array operations are used in feature engineering, mathematical transformations, and model calculations.

### Data Analytics Use Case

They can be used to compare, transform, and calculate numerical values in datasets.


## Step 3 – Implement the Concept (Python)

In [16]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 5])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** 2)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]
Power: [100 400 900]


## Code Explanation

### What the Code Does

The code performs different mathematical operations on two NumPy arrays.

### Why These Operations Are Used

- `a + b` performs element-wise addition.
- `a - b` performs element-wise subtraction.
- `a * b` performs element-wise multiplication.
- `a / b` performs element-wise division.
- `a ** 2` calculates the square of every element.

### Expected Output

```text
Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [20 80 150]
Division: [5. 5. 6.]
Power: [100 400 900]

# 16. Universal Functions (ufuncs)

## Step 1 – Understand the Concept

Universal functions, called **ufuncs**, are NumPy functions that perform mathematical operations efficiently on array elements.

Examples include:

- `np.sqrt()` → square root
- `np.square()` → square
- `np.abs()` → absolute value
- `np.exp()` → exponential
- `np.log()` → logarithm
- `np.sin()` → sine
- `np.cos()` → cosine

ufuncs can perform operations on complete arrays without writing a normal Python loop.

## Step 2 – Demonstrate the Concept

### Simple Example

For:

[1, 4, 9, 16]

We can use `np.sqrt()` to calculate the square root of every value.

Result:

[1, 2, 3, 4]

### Real-World Example

A scientific application may calculate square roots, logarithms, or other mathematical values for thousands of measurements.

### Business Example

A business analyst may apply mathematical transformations to sales, revenue, or customer data before analysis.

### AI/ML Use Case

Mathematical transformations such as logarithm, exponential, and square root are commonly used in feature engineering and model calculations.

### Data Analytics Use Case

ufuncs can efficiently transform large numerical datasets before visualization or statistical analysis.


## Step 3 – Implement the Concept (Python)

In [17]:
import numpy as np

numbers = np.array([1, 4, 9, 16])

square_root = np.sqrt(numbers)
square = np.square(numbers)
absolute = np.abs(np.array([-5, -10, 15]))

print("Square root:", square_root)
print("Square:", square)
print("Absolute:", absolute)

Square root: [1. 2. 3. 4.]
Square: [  1  16  81 256]
Absolute: [ 5 10 15]


## Code Explanation

### What the Code Does

The code applies different NumPy mathematical functions to numerical arrays.

### Why the Functions Are Used

- `np.sqrt()` calculates the square root of each element.
- `np.square()` calculates the square of each element.
- `np.abs()` returns the positive magnitude of each element.

### Expected Output

```text
Square root: [1. 2. 3. 4.]
Square: [  1  16  81 256]
Absolute: [ 5 10 15]