# Notebook 2 – NumPy Mathematical Operations

# 1. Sum

## Step 1 – Understand the Concept

Sum means adding all the values in a dataset or array.

NumPy provides the `np.sum()` function to calculate the total of array elements.

We can calculate the sum of all elements or calculate the sum along a particular axis.

## Step 2 – Demonstrate the Concept

### Simple Example

If the numbers are:

10, 20, 30

The sum is:

10 + 20 + 30 = 60

### Real-World Example

A student can calculate the total marks obtained in different subjects.

### Business Example

A company can calculate total sales made during a month by adding daily sales.

### AI/ML Use Case

Sum is used in mathematical calculations inside Machine Learning algorithms, such as calculating total values, distances, and losses.

### Data Analytics Use Case

Analysts can calculate total sales, total expenses, total customers, or other numerical totals.


## Step 3 – Implement the Concept (Python)

In [1]:
import numpy as np

sales = np.array([100, 200, 300, 400])

total_sales = np.sum(sales)

print("Sales:", sales)
print("Total Sales:", total_sales)

Sales: [100 200 300 400]
Total Sales: 1000


## Code Explanation

### What the Code Does

The code stores four sales values in a NumPy array and calculates their total.

### Why `np.sum()` Is Used

`np.sum()` adds all elements of the array and returns the total value.

### Expected Output

```text
Sales: [100 200 300 400]
Total Sales: 1000

# 2. Mean

## Step 1 – Understand the Concept

Mean is the average of a set of values.

The formula is:

Mean = Sum of all values / Number of values

NumPy provides the `np.mean()` function to calculate the mean

## Step 2 – Demonstrate the Concept

### Simple Example

For:

10, 20, 30

Mean = (10 + 20 + 30) / 3 = 20

### Real-World Example

A teacher can calculate the average marks of students in a class.

### Business Example

A company can calculate the average monthly sales to understand its typical sales performance.

### AI/ML Use Case

Mean is used in data preprocessing, feature scaling, and statistical analysis.

### Data Analytics Use Case

Mean helps analysts understand the central or typical value of numerical data.


## Step 3 – Implement the Concept (Python)

In [2]:
import numpy as np

marks = np.array([70, 80, 90, 60, 100])

average = np.mean(marks)

print("Marks:", marks)
print("Mean:", average)

Marks: [ 70  80  90  60 100]
Mean: 80.0


## Code Explanation

### What the Code Does

The code calculates the average marks of five students.

### Why `np.mean()` Is Used

`np.mean()` calculates the arithmetic average of all values in the array.

### Expected Output

```text
Marks: [ 70  80  90  60 100]
Mean: 80.0

# 3. Median

## Step 1 – Understand the Concept

Median is the middle value when data is arranged in ascending or descending order.

If there is an odd number of values, the middle value is the median.

If there is an even number of values, the median is the average of the two middle values.

NumPy provides `np.median()` to calculate the median.

## Step 2 – Demonstrate the Concept

### Simple Example

For:

10, 20, 30, 40, 50

The middle value is 30.

Therefore, the median is 30.

### Real-World Example

The median can be used to understand the typical income of people when a few people have extremely high salaries.

### Business Example

A company can use median salary to understand a typical employee's salary without being heavily affected by very high salaries.

### AI/ML Use Case

Median is useful when handling data containing outliers because it is less affected by extreme values than the mean.

### Data Analytics Use Case

Analysts use median to summarize skewed data such as income, property prices, or customer spending.


## Step 3 – Implement the Concept (Python)

In [3]:
import numpy as np

salaries = np.array([20000, 25000, 30000, 35000, 200000])

median_salary = np.median(salaries)

print("Salaries:", salaries)
print("Median Salary:", median_salary)

Salaries: [ 20000  25000  30000  35000 200000]
Median Salary: 30000.0


## Code Explanation

### What the Code Does

The code calculates the middle salary from the given salary values.

### Why `np.median()` Is Used

`np.median()` finds the middle value after considering the values in sorted order.

### Expected Output

```text
Salaries: [ 20000  25000  30000  35000 200000]
Median Salary: 30000.0

# 4. Variance

## Step 1 – Understand the Concept

Variance measures how much the values in a dataset differ from the mean.

A small variance means the values are close to the mean.

A large variance means the values are more spread out.

NumPy provides `np.var()` to calculate variance.

## Step 2 – Demonstrate the Concept

### Simple Example

Consider:

10, 10, 10

All values are the same, so the variance is 0.

Now consider:

5, 10, 15

The values are more spread out, so the variance is higher.

### Real-World Example

Variance can describe how much daily temperatures change from their average temperature.

### Business Example

A company can use variance to understand how much daily sales fluctuate around average sales.

### AI/ML Use Case

Variance is used to understand feature variability and is important in statistical methods and feature selection.

### Data Analytics Use Case

Variance helps analysts identify how consistent or inconsistent numerical data is.


## Step 3 – Implement the Concept (Python)

In [4]:
import numpy as np

sales = np.array([10, 20, 30, 40, 50])

variance = np.var(sales)

print("Sales:", sales)
print("Variance:", variance)

Sales: [10 20 30 40 50]
Variance: 200.0


## Code Explanation

### What the Code Does

The code calculates how much the sales values vary around their mean.

### Why `np.var()` Is Used

`np.var()` calculates the average squared difference between the values and their mean.

### Expected Output

```text
Sales: [10 20 30 40 50]
Variance: 200.0

# 5. Standard Deviation

## Step 1 – Understand the Concept

Standard deviation measures how much values are spread around the mean.

A low standard deviation means values are close to the mean.

A high standard deviation means values are more spread out.

Standard deviation is the square root of variance.

NumPy provides `np.std()` to calculate standard deviation.

## Step 2 – Demonstrate the Concept

### Simple Example

If students have marks:

49, 50, 51

The values are close to the mean, so the standard deviation is small.

If the marks are:

20, 50, 80

The values are more spread out, so the standard deviation is larger.

### Real-World Example

Standard deviation can show how much daily temperature changes around the average temperature.

### Business Example

A company can use standard deviation to measure how much daily sales fluctuate around average sales.

### AI/ML Use Case

Standard deviation is important in feature scaling, especially in standardization or z-score scaling.

### Data Analytics Use Case

It helps analysts understand the consistency and variability of numerical data.


## Step 3 – Implement the Concept (Python)

In [5]:
import numpy as np

sales = np.array([10, 20, 30, 40, 50])

std = np.std(sales)

print("Sales:", sales)
print("Standard Deviation:", std)

Sales: [10 20 30 40 50]
Standard Deviation: 14.142135623730951


## Code Explanation

### What the Code Does

The code calculates the standard deviation of the sales values.

### Why `np.std()` Is Used

`np.std()` calculates the standard deviation, which shows the amount of spread around the mean.

### Expected Output

```text
Sales: [10 20 30 40 50]
Standard Deviation: 14.142135623730951

# 6. Minimum

## Step 1 – Understand the Concept

Minimum means the smallest value in a dataset.

NumPy provides the `np.min()` function to find the smallest value in an array.

## Step 2 – Demonstrate the Concept

### Simple Example

For:

10, 5, 20, 15

The minimum value is 5.

### Real-World Example

A weather application can find the lowest temperature recorded during a day.

### Business Example

A company can find the lowest daily sales value in a month.

### AI/ML Use Case

Minimum values can be used during feature analysis and data preprocessing.

### Data Analytics Use Case

Analysts can identify the lowest sales, price, score, temperature, or other numerical value.


## Step 3 – Implement the Concept (Python)


In [6]:
import numpy as np

temperatures = np.array([32, 35, 29, 31, 36])

minimum = np.min(temperatures)

print("Temperatures:", temperatures)
print("Minimum Temperature:", minimum)

Temperatures: [32 35 29 31 36]
Minimum Temperature: 29


## Code Explanation

### What the Code Does

The code finds the smallest temperature in the array.

### Why `np.min()` Is Used

`np.min()` returns the smallest value in the array.

### Expected Output

```text
Temperatures: [32 35 29 31 36]
Minimum Temperature: 29

# 7. Maximum

## Step 1 – Understand the Concept

Maximum means the largest value in a dataset.

NumPy provides the `np.max()` function to find the largest value in an array.

## Step 2 – Demonstrate the Concept

### Simple Example

For:

10, 5, 20, 15

The maximum value is 20.

### Real-World Example

A weather application can identify the highest temperature recorded during a day.

### Business Example

A company can identify the highest sales amount achieved during a month.

### AI/ML Use Case

Maximum values are useful for understanding feature ranges and detecting unusually high values.

### Data Analytics Use Case

Analysts can identify highest sales, price, score, temperature, or other numerical values.


## Step 3 – Implement the Concept (Python)

In [7]:
import numpy as np

sales = np.array([1200, 1800, 1500, 2500, 2000])

maximum = np.max(sales)

print("Sales:", sales)
print("Maximum Sales:", maximum)

Sales: [1200 1800 1500 2500 2000]
Maximum Sales: 2500


## Code Explanation

### What the Code Does

The code finds the highest sales value.

### Why `np.max()` Is Used

`np.max()` returns the largest element in the array.

### Expected Output

```text
Sales: [1200 1800 1500 2500 2000]
Maximum Sales: 2500

# 8. Argmin

## Step 1 – Understand the Concept

`argmin` returns the **index position** of the smallest value in an array.

It does not return the minimum value itself.

NumPy provides `np.argmin()` for this purpose.

## Step 2 – Demonstrate the Concept

### Simple Example

For:

[40, 20, 30, 10]

The minimum value is 10.

Its index is 3.

Therefore:

`np.argmin()` → 3

### Real-World Example

A student can find which subject has the lowest marks by finding the index of the minimum mark.

### Business Example

A company can identify which month had the lowest sales using the index of the minimum value.

### AI/ML Use Case

Argmin is useful when selecting the position associated with the minimum cost, distance, error, or loss.

### Data Analytics Use Case

It helps identify the location of the lowest value in numerical data.


## Step 3 – Implement the Concept (Python)

In [8]:
import numpy as np

sales = np.array([400, 250, 500, 150, 350])

index = np.argmin(sales)

print("Sales:", sales)
print("Index of minimum sales:", index)
print("Minimum sales:", sales[index])

Sales: [400 250 500 150 350]
Index of minimum sales: 3
Minimum sales: 150


## Code Explanation

### What the Code Does

The code finds the position of the smallest sales value and then uses that position to retrieve the value.

### Why `np.argmin()` Is Used

`np.argmin()` returns the index of the smallest value.

### Expected Output

```text
Sales: [400 250 500 150 350]
Index of minimum sales: 3
Minimum sales: 150

# 9. Argmax

## Step 1 – Understand the Concept

`argmax` returns the **index position** of the largest value in an array.

It returns the position, not the maximum value itself.

NumPy provides `np.argmax()`.

## Step 2 – Demonstrate the Concept

### Simple Example

For:

[40, 20, 30, 50]

The maximum value is 50.

Its index is 3.

Therefore:

`np.argmax()` → 3

### Real-World Example

A teacher can find which subject has the highest marks.

### Business Example

A company can identify the month with the highest sales.

### AI/ML Use Case

Argmax is commonly used to select the class with the highest predicted probability in classification models.

### Data Analytics Use Case

It helps identify the position of the highest value in numerical data.


## Step 3 – Implement the Concept (Python)

In [9]:
import numpy as np

sales = np.array([400, 250, 500, 150, 350])

index = np.argmax(sales)

print("Sales:", sales)
print("Index of maximum sales:", index)
print("Maximum sales:", sales[index])

Sales: [400 250 500 150 350]
Index of maximum sales: 2
Maximum sales: 500


## Code Explanation

### What the Code Does

The code finds the position of the highest sales value and retrieves that value.

### Why `np.argmax()` Is Used

`np.argmax()` returns the index of the largest value.

### Expected Output

```text
Sales: [400 250 500 150 350]
Index of maximum sales: 2
Maximum sales: 500

# 10. Percentile

## Step 1 – Understand the Concept

A percentile tells us the value below which a certain percentage of observations fall.

For example, the 50th percentile is the median.

NumPy provides `np.percentile()` to calculate percentiles.

## Step 2 – Demonstrate the Concept

### Simple Example

Suppose we have student marks.

The 50th percentile represents the middle of the data.

The 90th percentile represents a value below which approximately 90% of the observations fall.

### Real-World Example

Entrance exam scores can be compared using percentiles to understand a student's position relative to other students.

### Business Example

A company can use the 90th percentile of delivery time to understand how long delivery takes for most customers.

### AI/ML Use Case

Percentiles are useful for detecting outliers and understanding feature distributions.

### Data Analytics Use Case

Percentiles help analyze customer spending, income, delivery times, response times, and other business metrics.


## Step 3 – Implement the Concept (Python)

In [10]:
import numpy as np

marks = np.array([50, 60, 70, 80, 90, 100])

p50 = np.percentile(marks, 50)
p90 = np.percentile(marks, 90)

print("50th Percentile:", p50)
print("90th Percentile:", p90)

50th Percentile: 75.0
90th Percentile: 95.0


## Code Explanation

### What the Code Does

The code calculates the 50th and 90th percentiles of student marks.

### Why `np.percentile()` Is Used

`np.percentile()` finds the value corresponding to a specified percentage position in the data.

### Expected Output

The 50th percentile is `75.0`.

The 90th percentile is approximately `95.0`.

### AI/ML Usage

Percentiles can be used for outlier detection, feature analysis, and understanding distributions.

### Data Analytics Usage

They are useful for understanding how data is distributed and identifying thresholds such as the top 10% of customers.

# 11. Dot Product

## Step 1 – Understand the Concept

The dot product combines corresponding values from two vectors by multiplying them and then adding the results.

For:

A = [a, b]

B = [c, d]

Dot Product = (a × c) + (b × d)

NumPy provides `np.dot()` to calculate the dot product.

## Step 2 – Demonstrate the Concept

### Simple Example

A = [2, 3]

B = [4, 5]

Dot Product:

(2 × 4) + (3 × 5) = 8 + 15 = 23

### Real-World Example

A dot product can represent a weighted score where each value has an importance or weight.

### Business Example

A company can calculate a customer score by multiplying customer feature values by their weights.

### AI/ML Use Case

Dot products are fundamental in Machine Learning. Linear regression, neural networks, and similarity calculations use dot products.

### Data Analytics Use Case

Dot products can be used for weighted calculations and numerical comparisons.


## Step 3 – Implement the Concept (Python)

In [11]:
import numpy as np

a = np.array([2, 3])
b = np.array([4, 5])

result = np.dot(a, b)

print("Dot Product:", result)

Dot Product: 23


## Code Explanation

### What the Code Does

The code calculates the dot product of two vectors.

### Why `np.dot()` Is Used

`np.dot()` multiplies corresponding values and adds the results.

### Expected Output

```text
Dot Product: 23

# 12. Matrix Multiplication

## Step 1 – Understand the Concept

Matrix multiplication combines two matrices using rows from the first matrix and columns from the second matrix.

The number of columns in the first matrix must equal the number of rows in the second matrix.

For example:

A has shape `(2, 2)`

B has shape `(2, 2)`

The result will have shape `(2, 2)`.

NumPy provides `np.matmul()` and the `@` operator for matrix multiplication.

## Step 2 – Demonstrate the Concept

### Simple Example

Consider:

A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]

The first result value is:

(1 × 5) + (2 × 7) = 19

### Real-World Example

Matrix multiplication can combine different sets of numerical information, such as transformations of coordinates.

### Business Example

A company can multiply a matrix of product quantities by a matrix of prices to calculate business values.

### AI/ML Use Case

Matrix multiplication is one of the most important operations in neural networks and Machine Learning models.

### Data Analytics Use Case

It can be used for mathematical transformations, weighted calculations, and numerical analysis.


## Step 3 – Implement the Concept (Python)

In [12]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = np.matmul(A, B)

print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

print("Matrix Multiplication:")
print(result)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Matrix Multiplication:
[[19 22]
 [43 50]]


## Code Explanation

### What the Code Does

The code multiplies two 2 × 2 matrices.

### Why `np.matmul()` Is Used

`np.matmul()` performs matrix multiplication according to the mathematical row-by-column rule.

### Expected Output

```text
Matrix Multiplication:
[[19 22]
 [43 50]]

# 13. Transpose

## Step 1 – Understand the Concept

Transpose changes the rows of a matrix into columns and the columns into rows.

For example:

Original:

[[1, 2, 3],
 [4, 5, 6]]

Transpose:

[[1, 4],
 [2, 5],
 [3, 6]]

NumPy provides `.T` and `np.transpose()` for transposing arrays.

## Step 2 – Demonstrate the Concept

### Simple Example

A matrix with 2 rows and 3 columns becomes a matrix with 3 rows and 2 columns after transposing.

### Real-World Example

A table containing students as rows and subjects as columns can be transposed to view subjects as rows.

### Business Example

A sales table can be rearranged so that products become rows and months become columns.

### AI/ML Use Case

Transpose is commonly used in matrix calculations, neural networks, and linear algebra operations.

### Data Analytics Use Case

Transpose can change the orientation of tabular numerical data for analysis.


## Step 3 – Implement the Concept (Python)

In [13]:
import numpy as np

data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

transposed = data.T

print("Original:")
print(data)

print("Transposed:")
print(transposed)

Original:
[[1 2 3]
 [4 5 6]]
Transposed:
[[1 4]
 [2 5]
 [3 6]]


## Code Explanation

### What the Code Does

The code changes the rows of the matrix into columns.

### Why `.T` Is Used

`.T` is a simple NumPy attribute used to return the transpose of an array.

### Expected Output

```text
Original:
[[1 2 3]
 [4 5 6]]

Transposed:
[[1 4]
 [2 5]
 [3 6]]

# 14. Basic Linear Algebra Operations

## Step 1 – Understand the Concept

Linear algebra is the study of vectors, matrices, and mathematical operations between them.

NumPy provides several functions for basic linear algebra operations.

Examples include:

- Matrix multiplication
- Dot product
- Transpose
- Inverse
- Determinant
- Solving linear equations

The `np.linalg` module provides many linear algebra functions.

## Step 2 – Demonstrate the Concept

### Simple Example

Consider a matrix:

[[1, 2],
 [3, 4]]

We can calculate properties such as its determinant or inverse.

### Real-World Example

Linear algebra is used to represent transformations such as changing the position, scale, or orientation of objects.

### Business Example

A company can use matrix-based calculations to solve resource allocation or pricing problems.

### AI/ML Use Case

Linear algebra is fundamental to Machine Learning. Regression, neural networks, dimensionality reduction, embeddings, and optimization use vectors and matrices.

### Data Analytics Use Case

Linear algebra can be used for numerical transformations, solving systems of equations, and working with structured numerical data.


## Step 3 – Implement the Concept (Python)

In [14]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

determinant = np.linalg.det(A)
inverse = np.linalg.inv(A)

print("Matrix:")
print(A)

print("Determinant:", determinant)

print("Inverse:")
print(inverse)

Matrix:
[[1 2]
 [3 4]]
Determinant: -2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]


## Code Explanation

### What the Code Does

The code calculates the determinant and inverse of a 2 × 2 matrix.

### Why the Functions Are Used

- `np.linalg.det()` calculates the determinant of a matrix.
- `np.linalg.inv()` calculates the inverse of a square matrix when an inverse exists.
- `np.linalg` is NumPy's linear algebra module.

### Expected Output

Approximately:

```text
Matrix:
[[1 2]
 [3 4]]

Determinant: -2.0

Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]